-- Badge Rules Migration
-- Extracted from /api/fun-facts endpoint in main.py
-- Migrates all hardcoded SQL badge queries into the badge_rules table
--
-- New schema:
--   id INTEGER PRIMARY KEY AUTOINCREMENT
--   badge_name TEXT NOT NULL UNIQUE
--   sql_query TEXT NOT NULL
--   result_type TEXT DEFAULT 'top'   -- 'top' = return top 1 row, 'count' = return count, 'boolean' = yes/no check
--   description TEXT
--   active INTEGER DEFAULT 1
--
-- result_type classification:
--   'top'      = queries with LIMIT 1 that return a ranked person
--   'count'    = queries returning aggregate counts (not yet used, but reserved)
--   'boolean'  = queries with HAVING/SUM/CASE checks that return a conditional result
--
-- Note: Queries that reference Python variables (cutoff_90, cutoff_30, cutoff_60, cutoff_7, today)
--       have been converted to use SQLite date functions or parameter placeholders {PARAM_N}.
--       The application layer should substitute these parameters before execution.
--       Placeholder mapping:
--         {PARAM_1} = cutoff_90 (summary_days, default 90 days)
--         {PARAM_2} = cutoff_30 (activity_days, default 30 days)
--         {PARAM_3} = cutoff_60 (long_streak_days, default 60 days)
--         {PARAM_4} = cutoff_7 (streak_days, default 7 days)
--         {PARAM_5} = today (current date)

-- ============================================================================
-- SECTION 1: Status-based badges (blocked, vague, in_progress, done, leave)
-- ============================================================================

INSERT OR IGNORE INTO badge_rules (badge_name, sql_query, result_type, description) VALUES
('Blocker Magnet', 'SELECT name, COUNT(*) as cnt FROM updates WHERE status=''blocked'' GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most blocked updates'),
('Vague Victor', 'SELECT name, COUNT(*) as cnt FROM updates WHERE status=''vague'' GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most vague updates'),
('Leave Taker', 'SELECT name, COUNT(*) as cnt FROM updates WHERE status = ''leave'' AND date >= {PARAM_1} GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most leave entries'),
('Done Streak', 'SELECT name, COUNT(*) as streak FROM (SELECT name, date, date(date, ''-'' || (ROW_NUMBER() OVER (PARTITION BY name ORDER BY date) - 1) || '' days'') as grp FROM updates WHERE status = ''done'' AND date >= {PARAM_2}) GROUP BY name, grp ORDER BY streak DESC LIMIT 1', 'top', 'Longest consecutive done days'),
('Blocker to Done', 'SELECT name, COUNT(*) as cnt FROM (SELECT a.name, a.module, a.date as blocked_date, b.date as done_date FROM updates a JOIN updates b ON a.name = b.name AND a.module = b.module WHERE a.status = ''blocked'' AND b.status = ''done'' AND b.date >= a.date AND b.date >= {PARAM_1}) GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most blocked tasks resolved to done'),
('Unblocker', 'SELECT name, COUNT(*) as cnt FROM updates a WHERE a.status = ''done'' AND EXISTS (SELECT 1 FROM updates b WHERE b.name = a.name AND b.module = a.module AND b.status = ''blocked'' AND b.date < a.date AND julianday(a.date) - julianday(b.date) <= 7) AND date >= {PARAM_1} GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Resolved blocked tasks within a week'),
('Reopener', 'SELECT name, COUNT(*) as cnt FROM updates WHERE status = ''in_progress'' AND module IN (SELECT module FROM updates u2 WHERE u2.name = updates.name AND u2.status = ''done'') AND date >= {PARAM_1} GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most reopened tasks'),
('Status Flipper', 'SELECT name, COUNT(*) as cnt FROM (SELECT name, module, date, status, LAG(status) OVER (PARTITION BY name, module ORDER BY date) as prev_status FROM updates WHERE date >= {PARAM_1}) WHERE status != prev_status AND prev_status IS NOT NULL GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most status changes'),
('Status Chameleon', 'SELECT name, COUNT(DISTINCT status) as cnt FROM updates WHERE date >= {PARAM_2} GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Uses the most distinct statuses'),
('Always In Progress', 'SELECT name, COUNT(*) as cnt FROM updates WHERE status = ''in_progress'' AND date >= {PARAM_2} GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most in_progress updates'),
('Always Done', 'SELECT name, COUNT(*) as cnt FROM updates WHERE status = ''done'' AND date >= {PARAM_2} GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most done updates'),
('Zero Blocked', 'SELECT name, COUNT(*) as total FROM updates WHERE date >= {PARAM_1} GROUP BY name HAVING SUM(CASE WHEN status = ''blocked'' THEN 1 ELSE 0 END) = 0 ORDER BY total DESC LIMIT 1', 'top', 'No blockers among active members'),
('First Today', 'SELECT name, MIN(created_at) as ts FROM updates WHERE date = {PARAM_5} GROUP BY name ORDER BY ts LIMIT 1', 'top', 'First person to submit today'),
('Last Today', 'SELECT name, MAX(created_at) as ts FROM updates WHERE date = {PARAM_5} GROUP BY name ORDER BY ts DESC LIMIT 1', 'top', 'Last person to submit today'),
('Daily Logger', 'SELECT name, COUNT(*) as cnt FROM updates WHERE date = {PARAM_5} GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most updates today'),
('Update Count Today', 'SELECT name, COUNT(*) as cnt FROM updates WHERE date = {PARAM_5} GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most updates submitted today');

-- ============================================================================
-- SECTION 2: Time-based badges (morning, evening, night, weekend, day-of-week)
-- ============================================================================

INSERT OR IGNORE INTO badge_rules (badge_name, sql_query, result_type, description) VALUES
('Peak Hour', 'SELECT strftime(''%H'', created_at) as hour, COUNT(*) as cnt FROM updates WHERE date >= {PARAM_1} GROUP BY strftime(''%H'', created_at) ORDER BY cnt DESC LIMIT 1', 'top', 'Peak update hour'),
('Power Day', 'SELECT CASE strftime(''%w'', date) WHEN ''0'' THEN ''Sunday'' WHEN ''1'' THEN ''Monday'' WHEN ''2'' THEN ''Tuesday'' WHEN ''3'' THEN ''Wednesday'' WHEN ''4'' THEN ''Thursday'' WHEN ''5'' THEN ''Friday'' WHEN ''6'' THEN ''Saturday'' END as day, COUNT(*) as cnt FROM updates WHERE status != ''leave'' AND date >= {PARAM_1} GROUP BY strftime(''%w'', date) ORDER BY cnt DESC LIMIT 1', 'top', 'Most active day of week'),
('Early Bird', 'SELECT name, AVG(CAST(strftime(''%H'', created_at) as REAL)) as avg_hour FROM updates WHERE date >= {PARAM_1} GROUP BY name ORDER BY avg_hour ASC LIMIT 1', 'top', 'Earliest average update time'),
('Clockwork', 'SELECT name, AVG((CAST(strftime(''%H'', created_at) as REAL) - 14) * (CAST(strftime(''%H'', created_at) as REAL) - 14)) as variance FROM updates WHERE date >= {PARAM_1} GROUP BY name HAVING COUNT(*) >= 5 ORDER BY variance ASC LIMIT 1', 'top', 'Most consistent update time'),
('Morning Person', 'SELECT name, COUNT(*) as cnt FROM updates WHERE strftime(''%H'', created_at) BETWEEN ''06'' AND ''09'' AND date >= {PARAM_1} GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most morning updates between 6-9 AM'),
('Lunch Skipper', 'SELECT name, COUNT(*) as cnt FROM updates WHERE strftime(''%H'', created_at) BETWEEN ''12'' AND ''14'' AND date >= {PARAM_1} GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most lunchtime updates'),
('Evening Person', 'SELECT name, COUNT(*) as cnt FROM updates WHERE strftime(''%H'', created_at) BETWEEN ''18'' AND ''23'' AND date >= {PARAM_1} GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most evening updates'),
('Midnight Oil', 'SELECT name, COUNT(*) as cnt FROM updates WHERE strftime(''%H'', created_at) BETWEEN ''22'' AND ''05'' AND date >= {PARAM_1} GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most late night updates'),
('Late Night Coder', 'SELECT name, COUNT(*) as cnt FROM updates WHERE strftime(''%H'', created_at) BETWEEN ''00'' AND ''04'' AND date >= {PARAM_1} GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most midnight to 4 AM updates'),
('Weekend Warrior', 'SELECT name, COUNT(*) as cnt FROM updates WHERE strftime(''%w'', date) IN (''0'', ''6'') AND status != ''leave'' AND date >= {PARAM_1} GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most weekend updates'),
('Monday Blues', 'SELECT name, COUNT(*) as cnt FROM updates WHERE strftime(''%w'', date) = ''1'' AND status = ''leave'' AND date >= {PARAM_1} GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most Monday leaves'),
('Friday Finisher', 'SELECT name, COUNT(*) as cnt FROM updates WHERE strftime(''%w'', date) = ''5'' AND status = ''done'' AND date >= {PARAM_1} GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most Friday done tasks'),
('Morning Streak', 'SELECT name, COUNT(*) as cnt FROM updates WHERE strftime(''%H'', created_at) BETWEEN ''08'' AND ''10'' AND date >= {PARAM_2} GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most morning updates 8-10 AM'),
('Afternoon Surge', 'SELECT name, COUNT(*) as cnt FROM updates WHERE strftime(''%H'', created_at) BETWEEN ''14'' AND ''17'' AND date >= {PARAM_2} GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most afternoon updates 2-5 PM'),
('Weekend Coder', 'SELECT name, COUNT(*) as cnt FROM updates WHERE strftime(''%w'', date) IN (''0'', ''6'') AND status != ''leave'' AND date >= {PARAM_1} GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Weekend coder'),
('Monday Starter', 'SELECT name, COUNT(*) as cnt FROM updates WHERE strftime(''%w'', date) = ''1'' AND status != ''leave'' AND date >= {PARAM_1} GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most Monday updates'),
('Tuesday Warrior', 'SELECT name, COUNT(*) as cnt FROM updates WHERE strftime(''%w'', date) = ''2'' AND status != ''leave'' AND date >= {PARAM_1} GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most Tuesday updates'),
('Wednesday Peak', 'SELECT name, COUNT(*) as cnt FROM updates WHERE strftime(''%w'', date) = ''3'' AND status != ''leave'' AND date >= {PARAM_1} GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most Wednesday updates'),
('Thursday Hustler', 'SELECT name, COUNT(*) as cnt FROM updates WHERE strftime(''%w'', date) = ''4'' AND status != ''leave'' AND date >= {PARAM_1} GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most Thursday updates'),
('Sunday Coder', 'SELECT name, COUNT(*) as cnt FROM updates WHERE strftime(''%w'', date) = ''0'' AND status != ''leave'' AND date >= {PARAM_1} GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most Sunday updates'),
('Productive Mornings', 'SELECT name, COUNT(*) as cnt FROM updates WHERE strftime(''%H'', created_at) BETWEEN ''06'' AND ''12'' AND status = ''done'' AND date >= {PARAM_1} GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most morning done tasks'),
('Night Fixer', 'SELECT name, COUNT(*) as cnt FROM updates WHERE strftime(''%H'', created_at) BETWEEN ''20'' AND ''23'' AND status = ''done'' AND date >= {PARAM_1} GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most night done tasks'),
('Break Taker', 'SELECT name, COUNT(*) as cnt FROM updates WHERE strftime(''%H'', created_at) BETWEEN ''12'' AND ''13'' AND date >= {PARAM_1} GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Updates during lunch break'),
('Dawn Patrol', 'SELECT name, COUNT(*) as cnt FROM updates WHERE strftime(''%H'', created_at) BETWEEN ''05'' AND ''08'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Early dawn updates'),
('Mid-Day Crunch', 'SELECT name, COUNT(*) as cnt FROM updates WHERE strftime(''%H'', created_at) BETWEEN ''11'' AND ''14'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most mid-day updates'),
('Afternoon Delight', 'SELECT name, COUNT(*) as cnt FROM updates WHERE strftime(''%H'', created_at) BETWEEN ''14'' AND ''17'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most afternoon updates'),
('Dusk Coder', 'SELECT name, COUNT(*) as cnt FROM updates WHERE strftime(''%H'', created_at) BETWEEN ''17'' AND ''20'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most dusk updates'),
('Lunch Break Skipper', 'SELECT name, COUNT(*) as cnt FROM updates WHERE strftime(''%H'', created_at) BETWEEN ''12'' AND ''13'' AND status != ''leave'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Works through lunch'),
('Tea Time Coder', 'SELECT name, COUNT(*) as cnt FROM updates WHERE strftime(''%H'', created_at) BETWEEN ''15'' AND ''16'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most tea time updates'),
('Happy Hour Hacker', 'SELECT name, COUNT(*) as cnt FROM updates WHERE strftime(''%H'', created_at) BETWEEN ''17'' AND ''19'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most happy hour updates'),
('Post-Dinner Dev', 'SELECT name, COUNT(*) as cnt FROM updates WHERE strftime(''%H'', created_at) BETWEEN ''20'' AND ''22'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most after-dinner updates'),
('Insomnia Coder', 'SELECT name, COUNT(*) as cnt FROM updates WHERE strftime(''%H'', created_at) BETWEEN ''00'' AND ''05'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most midnight to 5 AM updates'),
('Weekend Blocker', 'SELECT name, COUNT(*) as cnt FROM updates WHERE strftime(''%w'', date) IN (''0'', ''6'') AND status = ''blocked'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most weekend blockers'),
('Weekend Done', 'SELECT name, COUNT(*) as cnt FROM updates WHERE strftime(''%w'', date) IN (''0'', ''6'') AND status = ''done'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most weekend done tasks'),
('Friday Push', 'SELECT name, COUNT(*) as cnt FROM updates WHERE strftime(''%w'', date) = ''5'' AND status = ''done'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most Friday done tasks'),
('Monday Starter Pack', 'SELECT name, COUNT(*) as cnt FROM updates WHERE strftime(''%w'', date) = ''1'' AND status = ''in_progress'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most Monday in_progress tasks'),
('Tuesday Blues', 'SELECT name, COUNT(*) as cnt FROM updates WHERE strftime(''%w'', date) = ''2'' AND status = ''blocked'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most Tuesday blockers'),
('Wednesday Wonder', 'SELECT name, COUNT(*) as cnt FROM updates WHERE strftime(''%w'', date) = ''3'' AND status = ''done'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most Wednesday done tasks'),
('Thursday Thinker', 'SELECT name, COUNT(*) as cnt FROM updates WHERE strftime(''%w'', date) = ''4'' AND status = ''in_progress'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most Thursday in_progress tasks');

-- ============================================================================
-- SECTION 3: Module and productivity badges
-- ============================================================================

INSERT OR IGNORE INTO badge_rules (badge_name, sql_query, result_type, description) VALUES
('Module Explorer', 'SELECT name, COUNT(DISTINCT module) as cnt FROM updates WHERE module != '''' AND date >= {PARAM_1} GROUP BY name ORDER BY cnt DESC LIMIT 3', 'top', 'Works across most distinct modules'),
('Specialist', 'SELECT name, module, COUNT(*) as cnt, CAST(COUNT(*) as REAL) / (SELECT COUNT(*) FROM updates u2 WHERE u2.name = updates.name AND date >= {PARAM_1}) as pct FROM updates WHERE module != '''' AND date >= {PARAM_1} GROUP BY name, module ORDER BY pct DESC LIMIT 1', 'top', 'Highest module focus percentage'),
('Module Loyalist', 'SELECT name, module, COUNT(*) as cnt FROM updates WHERE module != '''' AND date >= {PARAM_1} GROUP BY name, module ORDER BY cnt DESC LIMIT 1', 'top', 'Most updates in a single module'),
('Module Switcher', 'SELECT name, COUNT(DISTINCT module) as cnt FROM updates WHERE module != '''' AND date >= {PARAM_2} GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most modules in 30 days'),
('Single Module Focus', 'SELECT name, COUNT(DISTINCT module) as cnt FROM updates WHERE module != '''' AND date >= {PARAM_2} GROUP BY name ORDER BY cnt ASC LIMIT 1', 'top', 'Least modules - focused on one'),
('Task Juggler', 'SELECT name, AVG(cnt) as avg_tasks FROM (SELECT name, date, COUNT(*) as cnt FROM updates WHERE status != ''leave'' AND date >= {PARAM_2} GROUP BY name, date) GROUP BY name ORDER BY avg_tasks DESC LIMIT 1', 'top', 'Highest average tasks per day'),
('Most Modules Single Day', 'SELECT name, date, COUNT(DISTINCT module) as cnt FROM updates WHERE module != '''' AND date >= {PARAM_1} GROUP BY name, date ORDER BY cnt DESC LIMIT 1', 'top', 'Most modules touched in a single day'),
('Productive Day', 'SELECT name, date, COUNT(*) as cnt FROM updates WHERE status != ''leave'' AND date >= {PARAM_1} GROUP BY name, date ORDER BY cnt DESC LIMIT 1', 'top', 'Most updates in a single day'),
('Momentum Builder', 'SELECT name, COUNT(*) as cnt FROM updates WHERE date >= {PARAM_4} AND status != ''leave'' GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most updates in last 7 days'),
('Quiet Achiever', 'SELECT name, COUNT(*) as cnt FROM updates WHERE status = ''done'' AND date >= {PARAM_2} GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most done tasks in 30 days'),
('First Week Done', 'SELECT name, COUNT(*) as cnt FROM updates WHERE status = ''done'' AND date >= {PARAM_4} GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most done tasks in last 7 days'),
('Module Maverick', 'SELECT name, COUNT(DISTINCT module) as cnt FROM updates WHERE module != '''' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most modules across 90 days'),
('Focused Specialist', 'SELECT name, module, COUNT(*) as cnt FROM updates WHERE module != '''' AND date >= date(''now'', ''-90 days'') GROUP BY name, module ORDER BY cnt DESC LIMIT 1', 'top', 'Most updates in one module'),
('Rapid Releaser', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%release%'' OR description LIKE ''%shipped%'' OR description LIKE ''%live%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most release mentions'),
('Consistency Score', 'SELECT name, (COUNT(DISTINCT date) * 100.0 / (julianday(''now'') - julianday(MIN(date)) + 1)) as score FROM updates WHERE status != ''leave'' AND date >= {PARAM_1} GROUP BY name ORDER BY score DESC LIMIT 1', 'top', 'Highest update consistency percentage'),
('Update Frequency', 'SELECT name, CAST(COUNT(*) as REAL) / COUNT(DISTINCT date) as freq FROM updates WHERE date >= {PARAM_1} GROUP BY name ORDER BY freq DESC LIMIT 1', 'top', 'Highest updates per day ratio'),
('Solo Worker', 'SELECT name, COUNT(DISTINCT date) as days FROM updates WHERE date >= {PARAM_2} GROUP BY name ORDER BY days ASC LIMIT 1', 'top', 'Fewest active days'),
('Team Player', 'SELECT name, COUNT(DISTINCT date) as days FROM updates WHERE date >= {PARAM_2} GROUP BY name ORDER BY days DESC LIMIT 1', 'top', 'Most active days');

-- ============================================================================
-- SECTION 4: Streak and consistency badges
-- ============================================================================

INSERT OR IGNORE INTO badge_rules (badge_name, sql_query, result_type, description) VALUES
('Longest Streak', 'SELECT name, COUNT(*) as streak FROM (SELECT name, date, date(date, ''-'' || (ROW_NUMBER() OVER (PARTITION BY name ORDER BY date) - 1) || '' days'') as grp FROM updates WHERE status != ''leave'' AND date >= {PARAM_3}) GROUP BY name, grp ORDER BY streak DESC LIMIT 1', 'top', 'Longest consecutive work streak'),
('Comeback Kid', 'SELECT name, MAX(julianday(date) - julianday(lag_date)) as gap FROM (SELECT name, date, LAG(date) OVER (PARTITION BY name ORDER BY date) as lag_date FROM updates WHERE status != ''leave'') WHERE lag_date IS NOT NULL ORDER BY gap DESC LIMIT 1', 'top', 'Longest gap between updates'),
('Vacation Mode', 'SELECT name, MAX(julianday(date) - julianday(prev_date)) as gap FROM (SELECT name, date, LAG(date) OVER (PARTITION BY name ORDER BY date) as prev_date FROM updates WHERE status != ''leave'') WHERE prev_date IS NOT NULL ORDER BY gap DESC LIMIT 1', 'top', 'Longest gap between updates'),
('Same Day Updates', 'SELECT name, COUNT(DISTINCT date) as days FROM updates WHERE date >= {PARAM_2} GROUP BY name HAVING COUNT(*) > COUNT(DISTINCT date) * 2 ORDER BY COUNT(*) DESC LIMIT 1', 'top', 'Multiple updates per day most often'),
('Consecutive Leave', 'SELECT name, COUNT(*) as streak FROM (SELECT name, date, date(date, ''-'' || (ROW_NUMBER() OVER (PARTITION BY name ORDER BY date) - 1) || '' days'') as grp FROM updates WHERE status = ''leave'') GROUP BY name, grp ORDER BY streak DESC LIMIT 1', 'top', 'Longest consecutive leave streak'),
('Consistent Daily', 'SELECT name, COUNT(DISTINCT date) as days FROM updates WHERE date >= date(''now'', ''-14 days'') AND status != ''leave'' GROUP BY name HAVING days >= 10 ORDER BY days DESC LIMIT 1', 'top', 'Updated most days in last 14 days'),
('Update Every Other Day', 'SELECT name, COUNT(DISTINCT date) as cnt FROM updates WHERE date >= {PARAM_2} GROUP BY name HAVING cnt >= 10 ORDER BY cnt DESC LIMIT 1', 'top', 'Most distinct active days'),
('Consistent Updater', 'SELECT name, COUNT(DISTINCT date) as days FROM updates WHERE date >= date(''now'', ''-30 days'') AND status != ''leave'' GROUP BY name ORDER BY days DESC LIMIT 1', 'top', 'Most active days in last 30 days'),
('Sporadic Updater', 'SELECT name, COUNT(DISTINCT date) as days FROM updates WHERE date >= date(''now'', ''-30 days'') AND status != ''leave'' GROUP BY name ORDER BY days ASC LIMIT 1', 'top', 'Fewest active days in last 30 days');

-- ============================================================================
-- SECTION 5: Description content badges (keywords, patterns)
-- ============================================================================

INSERT OR IGNORE INTO badge_rules (badge_name, sql_query, result_type, description) VALUES
('Link Sharer', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%http%'' GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most links shared in updates'),
('Emoji Fan', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description GLOB ''*[^\x20-\x7E]*'' GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most emoji usage'),
('Meeting Master', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%meeting%'' GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most meeting mentions'),
('Longest Description', 'SELECT name, description, LENGTH(description) as len FROM updates WHERE status != ''leave'' ORDER BY len DESC LIMIT 1', 'top', 'Longest update description'),
('Bug Mentions', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%bug%'' GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most bug mentions'),
('Empty Module', 'SELECT name, COUNT(*) as cnt FROM updates WHERE module = '''' OR module IS NULL GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most updates without module'),
('Negative Nancy', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%not working%'' OR description LIKE ''%broken%'' OR description LIKE ''%failed%'' AND date >= {PARAM_1} GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most negative language in updates'),
('Positive Patty', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%working%'' OR description LIKE ''%success%'' OR description LIKE ''%completed%'' AND date >= {PARAM_1} GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most positive language in updates'),
('Screenshot User', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%screenshot%'' OR description LIKE ''%image%'' OR description LIKE ''%picture%'' GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most screenshot mentions'),
('Code Paster', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%```%'' OR description LIKE ''%code:%'' GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most code snippets in updates'),
('Description Trend', 'SELECT name, AVG(LENGTH(description)) as avg_len FROM updates WHERE status != ''leave'' AND date >= {PARAM_1} GROUP BY name ORDER BY avg_len DESC LIMIT 1', 'top', 'Longest average description'),
('Detail Oriented', 'SELECT name, AVG(LENGTH(description)) as avg_len FROM updates WHERE status != ''leave'' AND date >= {PARAM_1} GROUP BY name HAVING COUNT(*) >= 5 ORDER BY avg_len DESC LIMIT 1', 'top', 'Longest average description with minimum 5 updates'),
('Quick Updater', 'SELECT name, COUNT(*) as cnt FROM updates WHERE LENGTH(description) < 50 AND date >= {PARAM_1} GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most short descriptions under 50 chars'),
('Panic Mode', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%urgent%'' OR description LIKE ''%asap%'' OR description LIKE ''%emergency%'' AND date >= {PARAM_1} GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most urgent/emergency mentions'),
('Collaborative', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%pair%'' OR description LIKE ''%collaborat%'' OR description LIKE ''%team%'' AND date >= {PARAM_1} GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most collaboration mentions'),
('Self Starter', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%started%'' OR description LIKE ''%initiat%'' OR description LIKE ''%created%'' AND date >= {PARAM_1} GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most initiative mentions'),
('Discussion Starter', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%discuss%'' OR description LIKE ''%review%'' OR description LIKE ''%feedback%'' AND date >= {PARAM_1} GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most discussion/review mentions'),
('Planning Guru', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%plan%'' OR description LIKE ''%roadmap%'' OR description LIKE ''%milestone%'' AND date >= {PARAM_1} GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most planning mentions'),
('Learning Mode', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%learn%'' OR description LIKE ''%study%'' OR description LIKE ''%research%'' AND date >= {PARAM_1} GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most learning mentions'),
('Hotfix Hero', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%hotfix%'' OR description LIKE ''%critical%'' OR description LIKE ''%fix%'' AND date >= {PARAM_1} GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most hotfix/critical mentions'),
('Milestone Crusher', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%milestone%'' OR description LIKE ''%deliver%'' OR description LIKE ''%complete%'' AND date >= {PARAM_1} GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most milestone mentions'),
('Description Bullet User', 'SELECT name, COUNT(*) as cnt FROM updates WHERE (description LIKE ''%\n-%'' OR description LIKE ''%\n•%'') AND date >= {PARAM_1} GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most bullet point usage in descriptions'),
('Capitals User', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description GLOB ''*[A-Z][A-Z][A-Z]*'' AND date >= {PARAM_1} GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most ALL CAPS usage'),
('Question Explorer', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%?%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most question marks in descriptions'),
('Exclamation Enthusiast', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%!%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most exclamation marks in descriptions'),
('Number Lover', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description GLOB ''*[0-9]*'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most numbers in descriptions'),
('Emoji Abuser', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description GLOB ''*[^\x20-\x7E]*'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most emoji in descriptions over 90 days'),
('URL Master', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%http%'' OR description LIKE ''%www.%%'' OR description LIKE ''%.com%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most URLs shared'),
('File Attacher', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%file%'' OR description LIKE ''%attach%'' OR description LIKE ''%upload%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most file/attachment mentions'),
('Markdown User', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%**%'' OR description LIKE ''%##%'' OR description LIKE ''%```%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most markdown formatting usage');

-- ============================================================================
-- SECTION 6: Technology-specific badges (tools, languages, frameworks)
-- ============================================================================

INSERT OR IGNORE INTO badge_rules (badge_name, sql_query, result_type, description) VALUES
('Documentation Hero', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%doc%'' OR description LIKE ''%document%'' OR description LIKE ''%readme%'' AND date >= {PARAM_1} GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most documentation mentions'),
('Refactor Fanatic', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%refactor%'' OR description LIKE ''%cleanup%'' OR description LIKE ''%optimize%'' AND date >= {PARAM_1} GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most refactoring mentions'),
('Test Addict', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%test%'' OR description LIKE ''%testing%'' OR description LIKE ''%unit test%'' AND date >= {PARAM_1} GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most testing mentions'),
('Deploy Master', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%deploy%'' OR description LIKE ''%release%'' OR description LIKE ''%production%'' AND date >= {PARAM_1} GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most deployment mentions'),
('Command Line User', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%npm%'' OR description LIKE ''%git%'' OR description LIKE ''%docker%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most CLI tool mentions'),
('Design Thinker', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%design%'' OR description LIKE ''%UI%'' OR description LIKE ''%UX%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most design mentions'),
('Backend Wizard', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%API%'' OR description LIKE ''%endpoint%'' OR description LIKE ''%database%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most backend mentions'),
('Frontend Ninja', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%component%'' OR description LIKE ''%CSS%'' OR description LIKE ''%React%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most frontend mentions'),
('Security Minded', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%security%'' OR description LIKE ''%auth%'' OR description LIKE ''%encrypt%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most security mentions'),
('Performance Optimizer', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%performance%'' OR description LIKE ''%speed%'' OR description LIKE ''%cache%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most performance mentions'),
('Database Tinkerer', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%database%'' OR description LIKE ''%schema%'' OR description LIKE ''%migration%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most database mentions'),
('API Builder', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%API%'' OR description LIKE ''%endpoint%'' OR description LIKE ''%REST%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most API mentions'),
('Mobile Dev', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%mobile%'' OR description LIKE ''%app%'' OR description LIKE ''%iOS%'' OR description LIKE ''%Android%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most mobile dev mentions'),
('DevOps Engineer', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%CI/CD%'' OR description LIKE ''%pipeline%'' OR description LIKE ''%deploy%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most DevOps mentions'),
('AI Enthusiast', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%AI%'' OR description LIKE ''%ML%'' OR description LIKE ''%model%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most AI/ML mentions'),
('Data Analyst', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%data%'' OR description LIKE ''%analytics%'' OR description LIKE ''%report%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most data mentions'),
('Cloud Architect', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%cloud%'' OR description LIKE ''%AWS%'' OR description LIKE ''%Azure%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most cloud mentions'),
('Meeting Marathon', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%meeting%'' OR description LIKE ''%standup%'' OR description LIKE ''%sync%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most meeting mentions'),
('Code Reviewer', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%review%'' OR description LIKE ''%PR%'' OR description LIKE ''%merge%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most code review mentions'),
('Standup Star', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%standup%'' OR description LIKE ''%daily%'' OR description LIKE ''%scrum%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most standup mentions'),
('Sprint Warrior', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%sprint%'' OR description LIKE ''%story%'' OR description LIKE ''%ticket%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most sprint/agile mentions'),
('Retrospective Fan', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%retro%'' OR description LIKE ''%retrospective%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most retrospective mentions'),
('Onboarding Helper', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%onboard%'' OR description LIKE ''%new member%'' OR description LIKE ''%orient%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most onboarding mentions'),
('Tech Explorer', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%experiment%'' OR description LIKE ''%prototype%'' OR description LIKE ''%spike%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most experimentation mentions'),
('Bug Hunter', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%bug%'' OR description LIKE ''%issue%'' OR description LIKE ''%defect%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most bug/issue mentions'),
('Feature Flagger', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%feature flag%'' OR description LIKE ''%toggle%'' OR description LIKE ''%flag%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most feature flag mentions'),
('Legacy Maintainer', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%legacy%'' OR description LIKE ''%maintenance%'' OR description LIKE ''%support%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most legacy/maintenance mentions'),
('Integration Master', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%integration%'' OR description LIKE ''%third-party%'' OR description LIKE ''%webhook%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most integration mentions'),
('Logging Expert', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%log%'' OR description LIKE ''%monitor%'' OR description LIKE ''%alert%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most logging/monitoring mentions'),
('Migration Hero', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%migrat%'' OR description LIKE ''%upgrade%'' OR description LIKE ''%version%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most migration/upgrade mentions'),
('Config Manager', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%config%'' OR description LIKE ''%settings%'' OR description LIKE ''%environment%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most config/settings mentions'),
('Dependency Updater', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%depend%'' OR description LIKE ''%package%'' OR description LIKE ''%library%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most dependency mentions'),
('Accessibility Advocate', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%access%'' OR description LIKE ''%a11y%'' OR description LIKE ''%WCAG%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most accessibility mentions'),
('i18n Master', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%i18n%'' OR description LIKE ''%local%'' OR description LIKE ''%translat%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most localization mentions'),
('Error Handler', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%error%'' OR description LIKE ''%exception%'' OR description LIKE ''%crash%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most error/crash mentions'),
('Late Night Debugger', 'SELECT name, COUNT(*) as cnt FROM updates WHERE strftime(''%H'', created_at) BETWEEN ''22'' AND ''04'' AND (description LIKE ''%bug%'' OR description LIKE ''%fix%'') AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most late night bug fix mentions'),
('Weekend Fixer', 'SELECT name, COUNT(*) as cnt FROM updates WHERE strftime(''%w'', date) IN (''0'', ''6'') AND (description LIKE ''%bug%'' OR description LIKE ''%fix%'') AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most weekend bug fix mentions');

-- ============================================================================
-- SECTION 7: Infrastructure/platform tool badges
-- ============================================================================

INSERT OR IGNORE INTO badge_rules (badge_name, sql_query, result_type, description) VALUES
('Jira User', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%jira%'' OR description LIKE ''%ticket%'' OR description LIKE ''%issue key%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most Jira mentions'),
('Slack User', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%slack%'' OR description LIKE ''%channel%'' OR description LIKE ''%thread%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most Slack mentions'),
('GitHub User', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%github%'' OR description LIKE ''%commit%'' OR description LIKE ''%branch%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most GitHub mentions'),
('Zoom User', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%zoom%'' OR description LIKE ''%call%'' OR description LIKE ''%video%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most Zoom/video mentions'),
('Email User', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%email%'' OR description LIKE ''%mail%'' OR description LIKE ''%inbox%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most email mentions'),
('Calendar User', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%calendar%'' OR description LIKE ''%schedule%'' OR description LIKE ''%event%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most calendar mentions'),
('Doc User', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%doc%'' OR description LIKE ''%confluence%'' OR description LIKE ''%wiki%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most doc/wiki mentions'),
('Figma User', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%figma%'' OR description LIKE ''%design file%'' OR description LIKE ''%mockup%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most Figma mentions'),
('Notion User', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%notion%'' OR description LIKE ''%page%'' OR description LIKE ''%database%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most Notion mentions'),
('Linear User', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%linear%'' OR description LIKE ''%cycle%'' OR description LIKE ''%project%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most Linear mentions'),
('Todoist User', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%todo%'' OR description LIKE ''%task list%'' OR description LIKE ''%checklist%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most todo mentions'),
('Postman User', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%postman%'' OR description LIKE ''%API test%'' OR description LIKE ''%endpoint%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most Postman mentions'),
('VSCode User', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%vscode%'' OR description LIKE ''%editor%'' OR description LIKE ''%IDE%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most VS Code mentions'),
('Terminal User', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%terminal%'' OR description LIKE ''%shell%'' OR description LIKE ''%bash%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most terminal mentions'),
('Docker User', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%docker%'' OR description LIKE ''%container%'' OR description LIKE ''%image%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most Docker mentions'),
('Kubernetes User', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%kubernetes%'' OR description LIKE ''%k8s%'' OR description LIKE ''%pod%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most Kubernetes mentions'),
('Terraform User', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%terraform%'' OR description LIKE ''%infrastructure%'' OR description LIKE ''%IaC%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most Terraform mentions'),
('Ansible User', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%ansible%'' OR description LIKE ''%playbook%'' OR description LIKE ''%config%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most Ansible mentions'),
('Jenkins User', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%jenkins%'' OR description LIKE ''%build%'' OR description LIKE ''%CI%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most Jenkins mentions'),
('Grafana User', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%grafana%'' OR description LIKE ''%dashboard%'' OR description LIKE ''%metric%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most Grafana mentions'),
('Prometheus User', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%prometheus%'' OR description LIKE ''%monitor%'' OR description LIKE ''%alert%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most Prometheus mentions'),
('Sentry User', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%sentry%'' OR description LIKE ''%error track%'' OR description LIKE ''%crash%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most Sentry mentions'),
('Datadog User', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%datadog%'' OR description LIKE ''%observ%'' OR description LIKE ''%APM%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most Datadog mentions'),
('Stripe User', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%stripe%'' OR description LIKE ''%payment%'' OR description LIKE ''%billing%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most Stripe mentions'),
('Auth0 User', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%auth0%'' OR description LIKE ''%auth%'' OR description LIKE ''%login%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most Auth0 mentions'),
('Firebase User', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%firebase%'' OR description LIKE ''%realtime%'' OR description LIKE ''%NoSQL%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most Firebase mentions'),
('Supabase User', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%supabase%'' OR description LIKE ''%postgres%'' OR description LIKE ''%realtime%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most Supabase mentions'),
('Redis User', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%redis%'' OR description LIKE ''%cache%'' OR description LIKE ''%key-value%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most Redis mentions'),
('Elasticsearch User', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%elastic%'' OR description LIKE ''%search%'' OR description LIKE ''%index%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most Elasticsearch mentions'),
('RabbitMQ User', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%rabbit%'' OR description LIKE ''%queue%'' OR description LIKE ''%message%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most RabbitMQ mentions'),
('Kafka User', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%kafka%'' OR description LIKE ''%stream%'' OR description LIKE ''%event%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most Kafka mentions'),
('GraphQL User', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%graphql%'' OR description LIKE ''%query%'' OR description LIKE ''%schema%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most GraphQL mentions'),
('REST User', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%REST%'' OR description LIKE ''%HTTP%'' OR description LIKE ''%API%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most REST mentions'),
('WebSocket User', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%websocket%'' OR description LIKE ''%socket%'' OR description LIKE ''%realtime%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most WebSocket mentions'),
('gRPC User', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%grpc%'' OR description LIKE ''%protobuf%'' OR description LIKE ''%RPC%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most gRPC mentions'),
('Microservices User', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%microservice%'' OR description LIKE ''%service%'' OR description LIKE ''%distributed%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most microservices mentions'),
('Monolith Maintainer', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%monolith%'' OR description LIKE ''%legacy%'' OR description LIKE ''%refactor%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most monolith mentions'),
('Event-Driven User', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%event%'' OR description LIKE ''%driven%'' OR description LIKE ''%async%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most event-driven mentions'),
('Serverless User', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%serverless%'' OR description LIKE ''%lambda%'' OR description LIKE ''%function%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most serverless mentions'),
('Edge Computing User', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%edge%'' OR description LIKE ''%CDN%'' OR description LIKE ''%worker%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most edge computing mentions'),
('WASM User', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%wasm%'' OR description LIKE ''%webassembly%'' OR description LIKE ''%rust%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most WASM mentions');

-- ============================================================================
-- SECTION 8: Programming language badges
-- ============================================================================

INSERT OR IGNORE INTO badge_rules (badge_name, sql_query, result_type, description) VALUES
('TypeScript User', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%typescript%'' OR description LIKE ''%type%'' OR description LIKE ''%interface%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most TypeScript mentions'),
('Python User', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%python%'' OR description LIKE ''%django%'' OR description LIKE ''%flask%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most Python mentions'),
('Go User', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%golang%'' OR description LIKE ''%go mod%'' OR description LIKE ''%goroutine%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most Go mentions'),
('Rust User', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%rust%'' OR description LIKE ''%cargo%'' OR description LIKE ''%borrow%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most Rust mentions'),
('Java User', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%java%'' OR description LIKE ''%spring%'' OR description LIKE ''%maven%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most Java mentions'),
('.NET User', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%.net%'' OR description LIKE ''%csharp%'' OR description LIKE ''%ASP%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most .NET mentions'),
('PHP User', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%php%'' OR description LIKE ''%laravel%'' OR description LIKE ''%composer%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most PHP mentions'),
('Ruby User', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%ruby%'' OR description LIKE ''%rails%'' OR description LIKE ''%gem%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most Ruby mentions'),
('Elixir User', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%elixir%'' OR description LIKE ''%phoenix%'' OR description LIKE ''%OTP%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most Elixir mentions'),
('Haskell User', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%haskell%'' OR description LIKE ''%monad%'' OR description LIKE ''%pure%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most Haskell mentions'),
('Scala User', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%scala%'' OR description LIKE ''%spark%'' OR description LIKE ''%akka%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most Scala mentions'),
('Kotlin User', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%kotlin%'' OR description LIKE ''%android%'' OR description LIKE ''%coroutine%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most Kotlin mentions'),
('Swift User', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%swift%'' OR description LIKE ''%iOS%'' OR description LIKE ''%Xcode%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most Swift mentions'),
('Dart User', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%dart%'' OR description LIKE ''%flutter%'' OR description LIKE ''%widget%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most Dart mentions'),
('Lua User', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%lua%'' OR description LIKE ''%neovim%'' OR description LIKE ''%script%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most Lua mentions'),
('Perl User', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%perl%'' OR description LIKE ''%cpan%'' OR description LIKE ''%regex%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most Perl mentions'),
('R User', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''% R %'' OR description LIKE ''%ggplot%'' OR description LIKE ''%shiny%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most R mentions'),
('MATLAB User', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%matlab%'' OR description LIKE ''%matrix%'' OR description LIKE ''%simulink%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most MATLAB mentions'),
('Julia User', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%julia%'' OR description LIKE ''% JuMP %'' OR description LIKE ''%DataFrame%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most Julia mentions'),
('Fortran User', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%fortran%'' OR description LIKE ''%numerical%'' OR description LIKE ''%HPC%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most Fortran mentions'),
('COBOL User', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%cobol%'' OR description LIKE ''%mainframe%'' OR description LIKE ''%legacy%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most COBOL mentions'),
('Assembly User', 'SELECT name, COUNT(*) as cnt FROM updates WHERE description LIKE ''%assembly%'' OR description LIKE ''%asm%'' OR description LIKE ''%register%'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most Assembly mentions');

-- ============================================================================
-- SECTION 9: Leave patterns and absence badges
-- ============================================================================

INSERT OR IGNORE INTO badge_rules (badge_name, sql_query, result_type, description) VALUES
('Most Leave Days', 'SELECT name, COUNT(*) as cnt FROM updates WHERE status = ''leave'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most total leave days in 90 days'),
('Least Leave Days', 'SELECT name, COUNT(*) as cnt FROM updates WHERE status = ''leave'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt ASC LIMIT 1', 'top', 'Fewest leave days in 90 days'),
('AL Collector', 'SELECT name, COUNT(*) as cnt FROM updates WHERE status = ''leave'' AND leave_type = ''AL'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most annual leave days'),
('MC Collector', 'SELECT name, COUNT(*) as cnt FROM updates WHERE status = ''leave'' AND leave_type = ''MC'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most medical leave days'),
('EL User', 'SELECT name, COUNT(*) as cnt FROM updates WHERE status = ''leave'' AND leave_type = ''EL'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most emergency leave days'),
('Leave Friday', 'SELECT name, COUNT(*) as cnt FROM updates WHERE status = ''leave'' AND strftime(''%w'', date) = ''5'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most Friday leaves'),
('Leave Monday', 'SELECT name, COUNT(*) as cnt FROM updates WHERE status = ''leave'' AND strftime(''%w'', date) = ''1'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most Monday leaves');

-- ============================================================================
-- SECTION 10: Advanced/complex badges (joins, windows, analytics)
-- ============================================================================

INSERT OR IGNORE INTO badge_rules (badge_name, sql_query, result_type, description) VALUES
('Fastest Done', 'SELECT a.name, julianday(b.date) - julianday(a.date) as days FROM updates a JOIN updates b ON a.name = b.name AND a.module = b.module WHERE a.status = ''in_progress'' AND b.status = ''done'' AND b.date >= a.date AND b.date >= {PARAM_1} ORDER BY days ASC LIMIT 1', 'top', 'Fastest task completion time'),
('Rapid Turnaround', 'SELECT a.name, MIN(julianday(b.date) - julianday(a.date)) as days FROM updates a JOIN updates b ON a.name = b.name AND a.module = b.module WHERE a.status = ''in_progress'' AND b.status = ''done'' AND b.date >= a.date AND b.date >= date(''now'', ''-90 days'') GROUP BY a.name ORDER BY days ASC LIMIT 1', 'top', 'Quickest resolution of in_progress to done'),
('Fresh Start', 'SELECT name, MIN(date) as first_date FROM updates GROUP BY name ORDER BY first_date DESC LIMIT 1', 'top', 'Newest team member'),
('Veteran', 'SELECT name, MIN(date) as first_date FROM updates GROUP BY name ORDER BY first_date ASC LIMIT 1', 'top', 'Longest serving team member'),
('Leave Adjacent', 'SELECT name, COUNT(*) as cnt FROM updates a WHERE a.status != ''leave'' AND EXISTS (SELECT 1 FROM updates b WHERE b.name = a.name AND b.status = ''leave'' AND b.date = date(a.date, ''-1 day'')) AND a.date >= {PARAM_1} GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most work days right after leave'),
('Post-Leave Comeback', 'SELECT name, COUNT(*) as cnt FROM updates a WHERE a.status = ''done'' AND EXISTS (SELECT 1 FROM updates b WHERE b.name = a.name AND b.status = ''leave'' AND b.date = date(a.date, ''-1 day'')) AND a.date >= {PARAM_1} GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most done tasks after returning from leave'),
('Phoenix Riser', 'SELECT name, COUNT(*) as cnt FROM updates a WHERE a.status = ''done'' AND date >= date(''now'', ''-90 days'') AND EXISTS (SELECT 1 FROM updates b WHERE b.name = a.name AND b.status = ''blocked'' AND b.date < a.date AND julianday(a.date) - julianday(b.date) <= 7) GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Overcame blockers within a week'),
('Steady Eddie', 'SELECT name, COUNT(DISTINCT date) as days, MAX(date) as last, MIN(date) as first FROM updates WHERE status != ''leave'' AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY (days * 100.0 / (julianday(last) - julianday(first) + 1)) DESC LIMIT 1', 'top', 'Most consistent update pace'),
('Multi-Task Day', 'SELECT name, date, COUNT(DISTINCT module) as cnt, COUNT(*) as total FROM updates WHERE status != ''leave'' AND date >= date(''now'', ''-90 days'') GROUP BY name, date HAVING cnt >= 3 ORDER BY total DESC LIMIT 1', 'top', 'Most modules in a single day with at least 3'),
('Big Jumper', 'SELECT name, MAX(gap) as max_gap FROM (SELECT name, date, julianday(date) - julianday(LAG(date) OVER (PARTITION BY name ORDER BY date)) as gap FROM updates WHERE status != ''leave'') WHERE gap IS NOT NULL GROUP BY name ORDER BY max_gap DESC LIMIT 1', 'top', 'Longest gap between non-leave updates'),
('Gap Filler', 'SELECT name, COUNT(*) as cnt FROM (SELECT name, date, julianday(date) - julianday(LAG(date) OVER (PARTITION BY name ORDER BY date)) as gap FROM updates WHERE status != ''leave'') WHERE gap IS NOT NULL AND gap <= 2 AND date >= date(''now'', ''-90 days'') GROUP BY name ORDER BY cnt DESC LIMIT 1', 'top', 'Most back-to-back work days'),
('First In Last Out', 'SELECT name, MIN(strftime(''%H'', created_at)) as first_hour, MAX(strftime(''%H'', created_at)) as last_hour FROM updates WHERE date >= date(''now'', ''-90 days'') GROUP BY name HAVING first_hour <= ''08'' AND last_hour >= ''19'' ORDER BY COUNT(*) DESC LIMIT 1', 'top', 'Updates from before 8 AM to after 7 PM'),
('Update Frequency High', 'SELECT name, CAST(COUNT(*) as REAL) / COUNT(DISTINCT date) as freq FROM updates WHERE date >= date(''now'', ''-30 days'') AND status != ''leave'' GROUP BY name ORDER BY freq DESC LIMIT 1', 'top', 'Highest update frequency in last 30 days'),
('Update Frequency Low', 'SELECT name, CAST(COUNT(*) as REAL) / NULLIF(COUNT(DISTINCT date), 0) as freq FROM updates WHERE date >= date(''now'', ''-30 days'') AND status != ''leave'' GROUP BY name ORDER BY freq ASC LIMIT 1', 'top', 'Lowest update frequency in last 30 days'),
('Longest Gap Overall', 'SELECT name, MAX(julianday(date) - julianday(prev_date)) as gap FROM (SELECT name, date, LAG(date) OVER (PARTITION BY name ORDER BY date) as prev_date FROM updates WHERE status != ''leave'') WHERE prev_date IS NOT NULL ORDER BY gap DESC LIMIT 1', 'top', 'Longest gap between updates overall');